### ISSUE TITLE
Segfault after sending many requests

### ISSUE THREAD

**Issue by GranPC** [Dabbleam/lobster#4]
I have no idea why or how this is happening, but it's fairly easy to reproduce. Open the app and send the same request a bunch of times in quick succession. You will eventually segfault:

```double free or corruption (fasttop)```

Here's a backtrace; it doesn't always look the exact same:

```
#0  0x00007ffff7266fb7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 93824991046385, 4294967298, 0 <repeats 13 times>}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ffff7268921 in __GI_abort () at abort.c:79
        save_stage = 1
        act = 
          {__sigaction_handler = {sa_handler = 0x70, sa_sigaction = 0x70}, sa_mask = {__val = {140737340234149, 0, 0, 93825012339984, 59, 93825012339968, 59, 80, 140737340248283, 93824991244632, 140737343732800, 140737488336832, 58, 58, 140737488336848, 140737488337136}}, sa_flags = -18480, sa_restorer = 0x1000}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff72b1967 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff73deb0d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
        ap = {{gp_offset = 24, fp_offset = 0, overflow_arg_area = 0x7fffffffb900, reg_save_area = 0x7fffffffb890}}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007ffff72b89da in malloc_printerr (str=str@entry=0x7ffff73e07d0 "double free or corruption (fasttop)") at malloc.c:5342
#4  0x00007ffff72c00f4 in _int_free (have_lock=0, p=0x7fffd4006c20, av=0x7fffd4000020) at malloc.c:4260
        idx = <optimized out>
        old = <optimized out>
        idx = <optimized out>
        old = <optimized out>
        old2 = <optimized out>
        old2 = <optimized out>
        fb = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        fwd = <optimized out>
        size = <optimized out>
        nextchunk = <optimized out>
        bck = <optimized out>
        ar_ptr = 0x7fffd4000020
        p = 0x7fffd4006c20
        hook = <optimized out>
        mem = 0x7fffd4006c30
        hook = <optimized out>
#5  0x00007ffff72c00f4 in __GI___libc_free (mem=0x7fffd4006c30) at malloc.c:3134
        ar_ptr = 0x7fffd4000020
        p = 0x7fffd4006c20
        hook = <optimized out>
        mem = 0x7fffd4006c30
        hook = <optimized out>
#6  0x00007ffff783276d in _dlerror_run (operate=operate@entry=0x7ffff78320d0 <dlsym_doit>, args=args@entry=0x7fffffffb9b0) at dlerror.c:158
        result = 0x7ffff7a340e0 <last_result>
#7  0x00007ffff7832166 in __dlsym (handle=<optimized out>, name=0x7ffff7fef1dc "g_value_get_type") at dlsym.c:70
        args = {handle = 0x5555556aa0c0, name = 0x7ffff7fef1dc "g_value_get_type", who = 0x7ffff399848e <g_module_symbol+126>, sym = 0x7ffff78326a8 <__dlerror+568>}
        result = <optimized out>
#8  0x00007ffff399848e in g_module_symbol () at /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
#9  0x00007ffff3e03297 in g_typelib_symbol () at /usr/lib/x86_64-linux-gnu/libgirepository-1.0.so.1
#10 0x00007ffff3dfcd3a in g_registered_type_info_get_g_type () at /usr/lib/x86_64-linux-gnu/libgirepository-1.0.so.1
#11 0x00007ffff402e866 in lgi_type_get_repotype (L=0x40000378, gtype=0, info=0x55555741c140) at core.c:161
#12 0x00007ffff403393c in lgi_marshal_2lua (L=L@entry=0x40000378, ti=ti@entry=0x55555741c190, ai=ai@entry=0x0, dir=dir@entry=GI_DIRECTION_OUT, transfer=transfer@entry=GI_TRANSFER_NOTHING, source=0x41470360, parent=1, ci=0x55555571bde0, args=0x41470358) at marshal.c:1316
        by_ref = 0
        info = 0x55555741c140
        type = GI_INFO_TYPE_STRUCT
        info_guard = 5
        own = 0
        tag = <optimized out>
        arg = 0x41470360
        __func__ = "lgi_marshal_2lua"
#13 0x00007ffff40347a6 in lgi_marshal_field (L=0x40000378, object=0x41470358, getmode=1, parent_arg=1, field_arg=<optimized out>, val_arg=3) at marshal.c:1522
        ti = 0x55555741c190
        to_remove = 4
        nret = <optimized out>
        pi = 0x55555571bde0
        field_addr = <optimized out>
        __func__ = "lgi_marshal_field"
#14 0x0000555555460117 in  ()
#15 0x00007ffff4034c0a in lgi_marshal_access (L=0x40000378, getmode=1, compound_arg=1, element_arg=2, val_arg=3) at marshal.c:1547
#16 0x0000555555460117 in  ()
#17 0x0000555555454fec in lua_pcall ()
#18 0x00007ffff402c0f1 in closure_callback (cif=<optimized out>, ret=0x7fffffffbf00, args=0x7fffffffbd50, closure_arg=<optimized out>) at callable.c:1226
        callable = 0x413d7980
        callable_index = 4
        closure = <optimized out>
        block = <optimized out>
        res = 0
        npos = 5
        i = <optimized out>
        stacktop = 2
        call = 1
        param = <optimized out>
        L = 0x40000378
        __func__ = "closure_callback"
#19 0x00007ffff347db4f in ffi_closure_unix64_inner () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#20 0x00007ffff347df16 in ffi_closure_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#21 0x00007ffff3bab0bd in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff3bbe00e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff3bc66f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff3bc710f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff347ddae in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#26 0x00007ffff347d71f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#27 0x00007ffff402d811 in callable_call (L=<optimized out>) at callable.c:922
        param = <optimized out>
        i = <optimized out>
        lua_argi = <optimized out>
        nret = <optimized out>
        caller_allocated = <optimized out>
        nargs = 1
        retval = 
          {v_boolean = 3, v_int8 = 3 '\003', v_uint8 = 3 '\003', v_int16 = 3, v_uint16 = 3, v_int32 = 3, v_uint32 = 3, v_int64 = 3, v_uint64 = 3, v_float = 4.20389539e-45, v_double = 1.4821969375237396e-323, v_short = 3, v_ushort = 3, v_int = 3, v_uint = 3, v_long = 3, v_ulong = 3, v_ssize = 3, v_size = 3, v_string = 0x3 <error: Cannot access memory at address 0x3>, v_pointer = 0x3}
        args = 0x7fffffffc4c0
        ffi_args = 0x7fffffffc480
        redirect_out = 0x7fffffffc4a0
        err = 0x0
        state_lock = 0x4003fe28
        callable = 0x413f1650
        __func__ = "callable_call"
#28 0x0000555555460117 in  ()
#29 0x0000555555454fec in lua_pcall ()
#30 0x00007ffff402c0f1 in closure_callback (cif=<optimized out>, ret=0x7fffffffc860, args=0x7fffffffc6b0, closure_arg=<optimized out>) at callable.c:1226
        callable = 0x413d4fa0
        callable_index = 6
        closure = <optimized out>
        block = <optimized out>
        res = 0
        npos = 5
        i = <optimized out>
        stacktop = 4
        call = 1
        param = <optimized out>
        L = 0x40000378
        __func__ = "closure_callback"
#31 0x00007ffff347db4f in ffi_closure_unix64_inner () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#32 0x00007ffff347df16 in ffi_closure_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#33 0x00007ffff3bab0bd in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff3bbe00e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff3bc608f in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff3bc710f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007fffec1b60f8 in gtk_accel_group_activate () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007fffec1b798d in gtk_accel_groups_activate () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007fffec4516d9 in gtk_window_activate_key () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007fffec4518e1 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007fffec2e58f7 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff3bab2f6 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x00007ffff3bc63ad in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff3bc710f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007fffec42d534 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#46 0x00007fffec2e293f in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#47 0x00007fffec2e4948 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007fffeef37765 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#49 0x00007fffeef67f92 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#50 0x00007ffff36cc537 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#51 0x00007ffff36cc770 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#52 0x00007ffff36cc7fc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#53 0x00007ffff317bf3d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#54 0x00007ffff347ddae in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#55 0x00007ffff347d71f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#56 0x00007ffff402d811 in callable_call (L=<optimized out>) at callable.c:922
        param = <optimized out>
        i = <optimized out>
        lua_argi = <optimized out>
        nret = <optimized out>
        caller_allocated = <optimized out>
        nargs = 3
        retval = 
          {v_boolean = 3, v_int8 = 3 '\003', v_uint8 = 3 '\003', v_int16 = 3, v_uint16 = 3, v_int32 = 3, v_uint32 = 3, v_int64 = 3, v_uint64 = 3, v_float = 4.20389539e-45, v_double = 1.4821969375237396e-323, v_short = 3, v_ushort = 3, v_int = 3, v_uint = 3, v_long = 3, v_ulong = 3, v_ssize = 3, v_size = 3, v_string = 0x3 <error: Cannot access memory at address 0x3>, v_pointer = 0x3}
        args = 0x7fffffffd590
        ffi_args = 0x7fffffffd530
        redirect_out = 0x7fffffffd560
        err = 0x0
        state_lock = 0x4003fe28
        callable = 0x40c8e068
        __func__ = "callable_call"
#57 0x0000555555460117 in  ()
#58 0x0000555555454fec in lua_pcall ()
#59 0x0000555555407bce in  ()
#60 0x000055555540899e in  ()
#61 0x0000555555460117 in  ()
#62 0x0000555555455129 in lua_cpcall ()
#63 0x00005555554076d6 in main ()
```

This smells like either threading shenanigans or the garbage collector acting up, but I honestly have no idea what's going on.

**Comment by GranPC** [comment]
Disabling the garbage collector did not make it any better (in fact, are LGI objects even garbage collected?) - this is ugly

**Comment by GranPC** [comment]
Doesn't happen anymore after installing a new OS. Closing for now. 🤷‍♀️
